version: '3'

services:
  LuftdatenBoxStarter:
    build:
      context: .
      dockerfile: amd64/Dockerfile
    image: s3ler/luftdatenboxstart:latest
    ports:
      - 80:80

  LuftdatenBoxStarterRaspberryPi:
    build:
      context: .
      dockerfile: arm32v7/Dockerfile
    image: s3ler/luftdatenboxstart:latest
    ports:
      - 80:80
